name: Main Kittygram Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Устанавливаем и flake8, и зависимости для тестов (pytest, pyyaml)
          pip install flake8==6.0.0 pytest pyyaml
          # Устанавливаем зависимости Django для pytest.ini
          pip install -r ./backend/requirements.txt

      - name: Test with flake8
        run: python -m flake8 backend/

      - name: Run project structure tests
        run: pytest

 
  build_and_push:
  name: Build and Push ${{ matrix.service }}
  runs-on: ubuntu-latest
  needs: tests
  strategy:
    matrix:
      service:
        - name: backend
          context: ./backend/
        - name: frontend
          context: ./frontend/
        - name: gateway
          context: ./nginx/

  steps:
    - name: Check out the repo
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push image
      uses: docker/build-push-action@v4
      with:
        context: ${{ matrix.service.context }}
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_${{ matrix.service.name }}:${{ github.sha }}
          ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_${{ matrix.service.name }}:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs:
      - build_and_push
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy docker-compose.production.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: docker-compose.production.yml
          target: "kittygram"

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd kittygram
            cat <<EOF > .env
            ${{ secrets.DOT_ENV }}
            EOF
            echo "DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}" >> .env
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | sudo docker login \
              -u "${{ secrets.DOCKERHUB_USERNAME }}" \
              --password-stdin
            export IMAGE_TAG=${{ github.sha }}
            sudo docker compose -f docker-compose.production.yml pull
            sudo docker compose -f docker-compose.production.yml up -d --remove-orphans
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py migrate
            sudo docker compose -f docker-compose.production.yml exec backend python manage.py collectstatic
            sudo docker compose -f docker-compose.production.yml exec backend cp -r /app/collected_static/. /backend_static/static/
            
  auto_tests:
    name: Run autotests after deploy
    runs-on: ubuntu-latest
    needs: deploy 
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytest pyyaml

      - name: Run API and DockerHub tests
        run: pytest

  telegram-notify:
    name: Send Telegram notification
    runs-on: ubuntu-latest
    needs: auto_tests
    if: always()
    steps:
      - name: Send success message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            Деплой Kittygram успешно завершен
            
            Пользователь: ${{ github.actor }}
            Коммит: ${{ github.sha }}
            
            Проект доступен по адресу:
            http://${{ secrets.HOST }}