# .github/workflows/main.yml

name: Main Kittygram Workflow

on:
  push:
    branches:
      - main

jobs:
  tests:
    name: Run tests and linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./backend/requirements.txt flake8==6.0.0

      - name: Test with flake8
        run: python -m flake8 backend/

  # --- Job для сборки backend ---
  build_backend_and_push_to_docker_hub:
    name: Build and Push backend
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push backend image
        uses: docker/build-push-action@v4
        with:
          context: ./backend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_backend:latest

  # --- Job для сборки frontend ---
  build_frontend_and_push_to_docker_hub:
    name: Build and Push frontend
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push frontend image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_frontend:latest

  # --- Job для сборки gateway ---
  build_gateway_and_push_to_docker_hub:
    name: Build and Push gateway
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push gateway image
        uses: docker/build-push-action@v4
        with:
          context: ./nginx/ # Убедитесь, что Dockerfile для gateway лежит в папке nginx/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/kittygram_gateway:latest

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs:
      # Job-ы, которые должны завершиться до начала deploy
      - build_backend_and_push_to_docker_hub
      - build_frontend_and_push_to_docker_hub
      - build_gateway_and_push_to_docker_hub
      
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Copy docker-compose.production.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          source: docker-compose.production.yml
          target: "kittygram"

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd kittygram
            
            # Создаем .env файл из секрета GitHub
            echo "${{ secrets.DOT_ENV }}" > .env
            
            # Экспортируем переменную с логином Docker Hub для Compose
            export DOCKERHUB_USERNAME=${{ secrets.DOCKERHUB_USERNAME }}

            # Скачиваем свежие версии образов из Docker Hub
            sudo docker-compose -f docker-compose.production.yml pull
            
            # Останавливаем старые контейнеры, если они были, и пересоздаем новые
            # Миграции применятся автоматически благодаря 'command' в backend-сервисе
            sudo docker-compose -f docker-compose.production.yml up -d
            
            # Удаляем старые, неиспользуемые образы
            sudo docker image prune -f