name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Select action'
        required: true
        default: 'plan'
        options:
          - plan
          - apply
          - destroy

jobs:
  terraform:
    runs-on: ubuntu-latest
    # Выносим переменные на уровень джобы, чтобы они были доступны всем шагам
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
      YC_TOKEN: ${{ secrets.YC_TOKEN }}
      YC_CLOUD_ID: ${{ secrets.YC_CLOUD_ID }}
      YC_FOLDER_ID: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
      TF_VAR_cloud_id: ${{ secrets.YC_CLOUD_ID }}
      TF_VAR_folder_id: ${{ secrets.YC_FOLDER_ID }}
      TF_VAR_ssh_key: ${{ secrets.SSH_KEY }}

    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Plan
        if: ${{ github.event.inputs.action == 'plan' }}
        run: terraform plan
        working-directory: ./infra

      - name: Terraform Apply
        if: ${{ github.event.inputs.action == 'apply' }}
        run: terraform apply -auto-approve
        working-directory: ./infra

      - name: Save IP
        if: ${{ github.event.inputs.action == 'apply' }}
        run: |
          # Вытаскиваем IP из вывода терраформа и убираем лишние кавычки
          VM_IP=$(terraform output -raw vm_public_ip)
          echo "$VM_IP" > vm-ip.txt
        working-directory: ./infra

      - name: Upload IP
        if: ${{ github.event.inputs.action == 'apply' }}
        uses: actions/upload-artifact@v3
        with:
          name: server-ip
          path: ./infra/vm-ip.txt

      - name: Terraform Destroy
        if: ${{ github.event.inputs.action == 'destroy' }}
        run: terraform destroy -auto-approve
        working-directory: ./infra